source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'SenseKit' do
    pod 'SHSProtoBuf', :git => 'git@github.com:hello/protobuf-objc.git'
    pod 'LGBluetooth', :git => 'git@github.com:hello/LGBluetooth.git'
    pod 'iOSDFULibrary'
    pod "SenseKit", :path => "../"
    
    target 'Tests' do
        inherit! :search_paths
        pod 'Kiwi'
        pod 'Nocilla'
    end
end
