source 'https://github.com/CocoaPods/Specs.git'

pod 'SHSProtoBuf', :git => 'git@github.com:hello/protobuf-objc.git'
pod 'LGBluetooth', :git => 'git@github.com:hello/LGBluetooth.git'
pod "SenseKit", :path => "../"

target 'Tests', :exclusive => true do
  pod 'Kiwi'
  pod 'Nocilla', :head

  post_install do |installer|
    target = installer.project.targets.find { |t| t.to_s == "Pods-Tests-Kiwi" }
    if (target)
      target.build_configurations.each do |config|
        s = config.build_settings['FRAMEWORK_SEARCH_PATHS'] || ['$(inherited)']
        s << '$(PLATFORM_DIR)/Developer/Library/Frameworks'
        config.build_settings['FRAMEWORK_SEARCH_PATHS'] = s
      end
    else
      puts "WARNING: Pods-Tests-Kiwi target not found"
    end
  end
end
