// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "ProtocolBuffers.h"

// @@protoc_insertion_point(imports)

@class SENSenseMessage;
@class SENSenseMessageBuilder;
@class SelectedWifiEndPoint;
@class SelectedWifiEndPointBuilder;
@class WifiEndPoint;
@class WifiEndPointBuilder;
#ifndef __has_feature
  #define __has_feature(x) 0 // Compatibility with non-clang compilers.
#endif // __has_feature

#ifndef NS_RETURNS_NOT_RETAINED
  #if __has_feature(attribute_ns_returns_not_retained)
    #define NS_RETURNS_NOT_RETAINED __attribute__((ns_returns_not_retained))
  #else
    #define NS_RETURNS_NOT_RETAINED
  #endif
#endif

typedef enum {
  ErrorTypeTimeOut = 0,
  ErrorTypeNetworkError = 1,
  ErrorTypeDeviceAlreadyPaired = 2,
  ErrorTypeInternalDataError = 3,
  ErrorTypeDeviceDatabaseFull = 4,
} ErrorType;

BOOL ErrorTypeIsValidValue(ErrorType value);

typedef enum {
  SENSenseMessageTypeSetTime = 0,
  SENSenseMessageTypeGetTime = 1,
  SENSenseMessageTypeSetWifiEndpoint = 2,
  SENSenseMessageTypeGetWifiEndpoint = 3,
  SENSenseMessageTypeSetAlarms = 4,
  SENSenseMessageTypeGetAlarms = 5,
  SENSenseMessageTypeSwitchToPairingMode = 6,
  SENSenseMessageTypeSwitchToNormalMode = 7,
  SENSenseMessageTypeStartWifiscan = 8,
  SENSenseMessageTypeStopWifiscan = 9,
  SENSenseMessageTypeGetDeviceId = 10,
  SENSenseMessageTypeEreasePairedPhone = 11,
  SENSenseMessageTypePairPill = 12,
  SENSenseMessageTypeError = 13,
} SENSenseMessageType;

BOOL SENSenseMessageTypeIsValidValue(SENSenseMessageType value);


@interface SensenseMessageRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

@interface WifiEndPoint : PBGeneratedMessage {
@private
  BOOL hasName_:1;
  BOOL hasSsid_:1;
  NSString* name;
  NSString* ssid;
}
- (BOOL) hasName;
- (BOOL) hasSsid;
@property (readonly, strong) NSString* name;
@property (readonly, strong) NSString* ssid;

+ (WifiEndPoint*) defaultInstance;
- (WifiEndPoint*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (WifiEndPointBuilder*) builder;
+ (WifiEndPointBuilder*) builder;
+ (WifiEndPointBuilder*) builderWithPrototype:(WifiEndPoint*) prototype;
- (WifiEndPointBuilder*) toBuilder;

+ (WifiEndPoint*) parseFromData:(NSData*) data;
+ (WifiEndPoint*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (WifiEndPoint*) parseFromInputStream:(NSInputStream*) input;
+ (WifiEndPoint*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (WifiEndPoint*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (WifiEndPoint*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface WifiEndPointBuilder : PBGeneratedMessageBuilder {
@private
  WifiEndPoint* result;
}

- (WifiEndPoint*) defaultInstance;

- (WifiEndPointBuilder*) clear;
- (WifiEndPointBuilder*) clone;

- (WifiEndPoint*) build;
- (WifiEndPoint*) buildPartial;

- (WifiEndPointBuilder*) mergeFrom:(WifiEndPoint*) other;
- (WifiEndPointBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (WifiEndPointBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasName;
- (NSString*) name;
- (WifiEndPointBuilder*) setName:(NSString*) value;
- (WifiEndPointBuilder*) clearName;

- (BOOL) hasSsid;
- (NSString*) ssid;
- (WifiEndPointBuilder*) setSsid:(NSString*) value;
- (WifiEndPointBuilder*) clearSsid;
@end

@interface SelectedWifiEndPoint : PBGeneratedMessage {
@private
  BOOL hasPassword_:1;
  BOOL hasEndPoint_:1;
  NSString* password;
  WifiEndPoint* endPoint;
}
- (BOOL) hasEndPoint;
- (BOOL) hasPassword;
@property (readonly, strong) WifiEndPoint* endPoint;
@property (readonly, strong) NSString* password;

+ (SelectedWifiEndPoint*) defaultInstance;
- (SelectedWifiEndPoint*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (SelectedWifiEndPointBuilder*) builder;
+ (SelectedWifiEndPointBuilder*) builder;
+ (SelectedWifiEndPointBuilder*) builderWithPrototype:(SelectedWifiEndPoint*) prototype;
- (SelectedWifiEndPointBuilder*) toBuilder;

+ (SelectedWifiEndPoint*) parseFromData:(NSData*) data;
+ (SelectedWifiEndPoint*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (SelectedWifiEndPoint*) parseFromInputStream:(NSInputStream*) input;
+ (SelectedWifiEndPoint*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (SelectedWifiEndPoint*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (SelectedWifiEndPoint*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface SelectedWifiEndPointBuilder : PBGeneratedMessageBuilder {
@private
  SelectedWifiEndPoint* result;
}

- (SelectedWifiEndPoint*) defaultInstance;

- (SelectedWifiEndPointBuilder*) clear;
- (SelectedWifiEndPointBuilder*) clone;

- (SelectedWifiEndPoint*) build;
- (SelectedWifiEndPoint*) buildPartial;

- (SelectedWifiEndPointBuilder*) mergeFrom:(SelectedWifiEndPoint*) other;
- (SelectedWifiEndPointBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (SelectedWifiEndPointBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasEndPoint;
- (WifiEndPoint*) endPoint;
- (SelectedWifiEndPointBuilder*) setEndPoint:(WifiEndPoint*) value;
- (SelectedWifiEndPointBuilder*) setEndPointBuilder:(WifiEndPointBuilder*) builderForValue;
- (SelectedWifiEndPointBuilder*) mergeEndPoint:(WifiEndPoint*) value;
- (SelectedWifiEndPointBuilder*) clearEndPoint;

- (BOOL) hasPassword;
- (NSString*) password;
- (SelectedWifiEndPointBuilder*) setPassword:(NSString*) value;
- (SelectedWifiEndPointBuilder*) clearPassword;
@end

@interface SENSenseMessage : PBGeneratedMessage {
@private
  BOOL hasAccountId_:1;
  BOOL hasVersion_:1;
  BOOL hasSelectedWifiendPoint_:1;
  BOOL hasDeviceId_:1;
  BOOL hasType_:1;
  BOOL hasError_:1;
  long long accountId;
  long version;
  SelectedWifiEndPoint* selectedWifiendPoint;
  NSData* deviceId;
  SENSenseMessageType type;
  ErrorType error;
}
- (BOOL) hasVersion;
- (BOOL) hasType;
- (BOOL) hasSelectedWifiendPoint;
- (BOOL) hasDeviceId;
- (BOOL) hasAccountId;
- (BOOL) hasError;
@property (readonly) long version;
@property (readonly) SENSenseMessageType type;
@property (readonly, strong) SelectedWifiEndPoint* selectedWifiendPoint;
@property (readonly, strong) NSData* deviceId;
@property (readonly) long long accountId;
@property (readonly) ErrorType error;

+ (SENSenseMessage*) defaultInstance;
- (SENSenseMessage*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (SENSenseMessageBuilder*) builder;
+ (SENSenseMessageBuilder*) builder;
+ (SENSenseMessageBuilder*) builderWithPrototype:(SENSenseMessage*) prototype;
- (SENSenseMessageBuilder*) toBuilder;

+ (SENSenseMessage*) parseFromData:(NSData*) data;
+ (SENSenseMessage*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (SENSenseMessage*) parseFromInputStream:(NSInputStream*) input;
+ (SENSenseMessage*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (SENSenseMessage*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (SENSenseMessage*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface SENSenseMessageBuilder : PBGeneratedMessageBuilder {
@private
  SENSenseMessage* result;
}

- (SENSenseMessage*) defaultInstance;

- (SENSenseMessageBuilder*) clear;
- (SENSenseMessageBuilder*) clone;

- (SENSenseMessage*) build;
- (SENSenseMessage*) buildPartial;

- (SENSenseMessageBuilder*) mergeFrom:(SENSenseMessage*) other;
- (SENSenseMessageBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (SENSenseMessageBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasVersion;
- (long) version;
- (SENSenseMessageBuilder*) setVersion:(long) value;
- (SENSenseMessageBuilder*) clearVersion;

- (BOOL) hasType;
- (SENSenseMessageType) type;
- (SENSenseMessageBuilder*) setType:(SENSenseMessageType) value;
- (SENSenseMessageBuilder*) clearType;

- (BOOL) hasSelectedWifiendPoint;
- (SelectedWifiEndPoint*) selectedWifiendPoint;
- (SENSenseMessageBuilder*) setSelectedWifiendPoint:(SelectedWifiEndPoint*) value;
- (SENSenseMessageBuilder*) setSelectedWifiendPointBuilder:(SelectedWifiEndPointBuilder*) builderForValue;
- (SENSenseMessageBuilder*) mergeSelectedWifiendPoint:(SelectedWifiEndPoint*) value;
- (SENSenseMessageBuilder*) clearSelectedWifiendPoint;

- (BOOL) hasDeviceId;
- (NSData*) deviceId;
- (SENSenseMessageBuilder*) setDeviceId:(NSData*) value;
- (SENSenseMessageBuilder*) clearDeviceId;

- (BOOL) hasAccountId;
- (long long) accountId;
- (SENSenseMessageBuilder*) setAccountId:(long long) value;
- (SENSenseMessageBuilder*) clearAccountId;

- (BOOL) hasError;
- (ErrorType) error;
- (SENSenseMessageBuilder*) setError:(ErrorType) value;
- (SENSenseMessageBuilder*) clearError;
@end


// @@protoc_insertion_point(global_scope)
